# Generated by Django 3.0.5 on 2020-04-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200409_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewies',
            new_name='Reviews',
        ),
    ]
